USER=www
CGIBASE=/Library/WebServer/CGI-Executables
URLBASE=/Library/WebServer/Documents/vitrite
LIBPATH=/usr/local/lib/vitrite
PERLLIBPATH=/Library/Perl/5.18/vitrite
DBPATH="/Library/Application Support/vitrite"

