include ../../Makefile.settings
LDFLAGS= -L/usr/local/opt/berkeley-db4/lib -lm -ldb #-lmd
RECIPE		=./RECIPE-C
CFLAGS		:=-g $(CFLAGS) -I./$(RECIPE) -I/usr/local/opt/berkeley-db4/include -I/usr/local/opt/openssl/include

depend: $(wildcard *.c *.h)
	$(CPP) $(CFLAGS) -MM $^ > .depend
clean:
	-rm *.o $(BINTARGET)
install: $(TARGET)
	install -m 0755 -o $(USER) -d $(LIBPATH)
	install -m 0755 -o $(USER) $(TARGET) $(LIBPATH)
